#services:
#  postgres:
#    image: 'postgres:latest'
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
#    environment:
#      - 'POSTGRES_DB=share-hub-db'
#      - 'POSTGRES_PASSWORD=secret'
#      - 'POSTGRES_USER=admin'
#    ports:
#      - '5432:5432'
#    restart: on-failure
services:
  app:
    image: blog-post-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-api
    restart: on-failure
    ports:
      - "8000:8000"
